### ISSUE TITLE
mongo-connector with elasticsearch does not work when dynamic mapping is set to strict in elastcsearch

### ISSUE THREAD

**Issue by vvaradhan** [10gen-labs/mongo-connector#138]
In my application, each document can have about 500+ fields and not all of them are present in each document.  One of the primary reasons to choose mongodb.  Out of this 500+ fields, only a handful (say 20) fields are index fields and they are indexed in elasticsearch.

A field mapping file is configured in elasticsearch for the target index.  When mongo-connector tries to push documents to elasticsearch, elasticsearch throws an exception as follows: 
org.elasticsearch.index.mapper.StrictDynamicMappingException: mapping set to strict, dynamic introduction of [xdasprov] within [string] is not allowed
	at org.elasticsearch.index.mapper.object.ObjectMapper.parseDynamicValue(ObjectMapper.java:648)
	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:638)
	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:489)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:515)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:462)
	at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:394)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:194)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:534)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:433)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

After receiving this exception, mongo-connector does not work at all.

Solr doc manager used to read Solr's schema xml and restrict field set accordingly before pushing documents to Solr.  

Can something of that sort be done for elasticsearch doc manager?

**Comment by lovett89** [comment]
The feature that this issue describes is described in #140, so I'm closing this issue. Feel free to reopen if there's anything unresolved and undocumented in #140.

**Comment by fanyoujian** [comment]
this my mapping ：
{
    "mappings": {
        "addata_index": {
            "dynamic": "strict",
            "_all": {
                "enabled": false
            },
            "properties": {
                "attribute07": {
                    "properties": {
                        "meta": {
                            "properties": {
                                "x": {
                                    "type": "string"
                                },
                                "y": {
                                    "type": "string"
                                }
                            }
                        },
                        "width": {
                            "type": "long"
                        }
                    }
                },
                "id": {
                    "type": "long"
                }
            }
        },
        "_default_": {
            "dynamic": "strict"
        }
    }
}

When I import es data when the error：
why is errors: [StrictDynamicMappingException[mapping set to strict, dynamic introduction of [height] within [attribute07] is not allowed]]
