### ISSUE TITLE
mongo-connector with elasticsearch fails to update a document in elasticsearch when "_source":false in the target mapping in ES

### ISSUE THREAD

**Issue by vvaradhan** [10gen-labs/mongo-connector#143]
In my index mapping, I have set "_source" to false.  I am not sure, whether this is the reason why my updates are not getting synced by mongo-connector, however, the exception /stacktrace points to something of this sort.

2014-07-02 19:24:36,156 - INFO - PUT http://localhost:9200/analytics.alerts/string/8019C821-E24B-1031-90EA-005056A54F88?refresh=false [status:201 request:0.004s]
2014-07-02 19:24:37,273 - INFO - GET http://localhost:9200/analytics.alerts/_all/8019C821-E24B-1031-90EA-005056A54F88 [status:200 request:0.004s]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 522, in __bootstrap_inner
    self.run()
  File "build/bdist.linux-x86_64/egg/mongo_connector/oplog_manager.py", line 225, in run
    docman.update(doc, entry.get('o', {}))
  File "build/bdist.linux-x86_64/egg/mongo_connector/doc_managers/__init__.py", line 24, in wrapped
  File "doc_managers/elastic_doc_manager.py", line 68, in update
    updated = self.apply_update(document['_source'], update_spec)
KeyError: '_source'

Let me know how I could get more details to get this resolved.

**Comment by lovett89** [comment]
Closing this. This question is now part of the [FAQ](https://github.com/10gen-labs/mongo-connector/wiki/FAQ)
