### ISSUE TITLE
'None' Where Variable in apply_update()

### ISSUE THREAD

**Issue by thelok** [10gen-labs/mongo-connector#188]
I guess you could call this a continuation of issue #163 

Encountered this using the elastic search doc manager:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "build/bdist.linux-x86_64/egg/mongo_connector/oplog_manager.py", line 237, in run
    docman.update(doc, entry.get('o', {}))
  File "build/bdist.linux-x86_64/egg/mongo_connector/doc_managers/__init__.py", line 24, in wrapped
    return f(*args, **kwargs)
  File "/data/mongo-connector/mongo_connector/doc_managers/elastic_doc_manager.py", line 84, in update
    updated = self.apply_update(document['_source'], update_spec)
  File "/data/mongo-connector/mongo_connector/doc_managers/elastic_doc_manager.py", line 74, in apply_update
    return super(DocManager, self).apply_update(doc, update_spec)
  File "build/bdist.linux-x86_64/egg/mongo_connector/doc_managers/__init__.py", line 85, in apply_update
    wl = len(where)
TypeError: object of type 'NoneType' has no len()
```

This was using the private no-timeout branch. We are using a sharded mongo DB.

**Comment by lovett89** [comment]
Resolved in the master and 2.0-dev branches in 75fe1a55163975b80ee406d28f61afa3c008f83e and 8f62851396245a3068cee847a5884d73146750c0, respectively. Thanks for reporting this.
