### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by crashbtz** [10gen-labs/mongo-connector#201]
Hello,

I try to index in SOLR
I have a problem with the first run of mongo-connector.

I use the mongo-connector 1.3.1, mongoDB 2.4.9 and SOLR 4.6
Solr run with 8Go RAM
And I've finally setted the DEFAULT_MAX_BULK to 5

Each time I run:

mongo-connector --auto-commit-interval=0 -m mongodb://<user>:<password>@<host>:<port>/<db> -t http://<url-solr>:<port-solr>/solr/<core> -d /path/to/solr_doc_manager_131.py -n <db>.<collections> --unique-key=id -o /path/to/config.txt -v

I have:
.
.
.
2014-12-22 17:29:40,897 - DEBUG - Starting to build add request...
2014-12-22 17:29:43,779 - DEBUG - Built add request of 5 docs in 2.88 seconds.
2014-12-22 17:29:43,891 - DEBUG - Starting request to 'http://host:port/solr/core/update/?commit=true' (post) with body 'u'<add com'...
2014-12-22 17:29:51,829 - DEBUG - "POST /solr/core/update/?commit=true HTTP/1.1" 200 None
2014-12-22 17:29:51,830 - INFO - Finished 'http://host:port/solr/core/update/?commit=true' (post) with body 'u'<add com' in 7.939 seconds.
2014-12-22 17:29:57,601 - DEBUG - Starting to build add request...
2014-12-22 17:30:05,727 - DEBUG - Built add request of 5 docs in 8.12 seconds.
2014-12-22 17:30:06,163 - DEBUG - Starting request to 'http://host:port/solr/core/update/?commit=true' (post) with body 'u'<add com'...
2014-12-22 17:31:15,189 - ERROR - Connection to server 'http://host:port/solr/core/update/?commit=true' timed out: HTTPConnectionPool(host='host', port=port): Read timed out. (read timeout=60)
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/pysolr.py", line 302, in _send_request
    timeout=self.timeout)
  File "/usr/local/lib64/python2.6/site-packages/requests-2.5.0-py2.6.egg/requests/sessions.py", line 504, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib64/python2.6/site-packages/requests-2.5.0-py2.6.egg/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib64/python2.6/site-packages/requests-2.5.0-py2.6.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib64/python2.6/site-packages/requests-2.5.0-py2.6.egg/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='host', port=port): Read timed out. (read timeout=60)
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/mongo_connector/oplog_manager.py", line 464, in do_dump
    upsert_all(dm)
  File "build/bdist.linux-x86_64/egg/mongo_connector/oplog_manager.py", line 448, in upsert_all
    dm.bulk_upsert(docs_to_dump())
  File "build/bdist.linux-x86_64/egg/mongo_connector/doc_managers/__init__.py", line 35, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "build/bdist.linux-x86_64/egg/mongo_connector/doc_managers/__init__.py", line 24, in wrapped
    return f(*args, **kwargs)
  File "/root/solr_doc_manager_131.py", line 241, in bulk_upsert
    self.solr.add(batch, **add_kwargs)
  File "build/bdist.linux-x86_64/egg/pysolr.py", line 779, in add
    return self._update(m, commit=commit, waitFlush=waitFlush, waitSearcher=waitSearcher)
  File "build/bdist.linux-x86_64/egg/pysolr.py", line 387, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "build/bdist.linux-x86_64/egg/pysolr.py", line 306, in _send_request
    raise SolrError(error_message % (url, err))
OperationFailed: Connection to server 'http://host:port/solr/core/update/?commit=true' timed out: HTTPConnectionPool(host='host', port=port): Read timed out. (read timeout=60)
2014-12-22 17:31:15,191 - ERROR - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient([u'prj-lb2mongosdr:9999', u'prj-clmdbsdr01:9999']), u'local'), u'oplog.rs')
2014-12-22 17:31:15,191 - DEBUG - OplogThread: Last entry is the one we already processed.  Up to date.  Sleeping.
2014-12-22 17:31:15,810 - ERROR - MongoConnector: OplogThread <OplogThread(Thread-2, started 140015789393664)> unexpectedly stopped! Shutting down
2014-12-22 17:31:15,810 - INFO - MongoConnector: Stopping all OplogThreads
2014-12-22 17:31:15,810 - DEBUG - OplogThread: exiting due to join call.

So that run just few minutes and crash

But when I crawl with LucidWorks that works perfectly

Thank you for your help

**Comment by lovett89** [comment]
Hi @crashbtz 
Are you still able to connect to Solr at all after the read timeout reported by Mongo Connector? Could you please provide the relevant logs from Solr as well? Thanks.

**Comment by crashbtz** [comment]
Hi,
Thank you for your response.
I found what was wrong. The mongo documents I tried to index were too large and the logs from Solr said something like "OutMemoryException".
Now I only index the fields I need and that works fine.

And to answer your question, I was not able to connect solr after the read timout cause solr has crashed, so I had to restart it.

sorry for the inconvenience

**Comment by lovett89** [comment]
No worries. Glad you got your problem solved!

**Comment by Khsaf** [comment]
Thanks for the hint @crashbtz. Increasing Solr heap and memory size seems to fixe my issue too. 

I changed `solr.in.sh` script

`
SOLR_HEAP="16g"
SOLR_JAVA_MEM="-Xms512m -Xmx16g"
`
