### ISSUE TITLE
Keyfile authentification failed

### ISSUE THREAD

**Issue by crashbtz** [10gen-labs/mongo-connector#204]
Hi,
I'm trying to use the keyFile authentification, but whathever I do I have "failed: auth failed" message.

What roles the admin user needs to have and on which database? And how do I need to generate the keyFile?

Here my user:
{
        "_id" : "admin.ced",
        "user" : "ced",
        "db" : "admin",
        "credentials" : {
                "MONGODB-CR" : "fd90c22024a2bc5cf47e9507bfa49790"
        },
        "roles" : [
                {
                        "role" : "userAdminAnyDatabase",
                        "db" : "admin"
                },
                {
                        "role" : "root",
                        "db" : "admin"
                }
        ]
}

and I generated the keyFile like that:
    > openssl rand -base64 741 > mongodb-keyfile

and start my replica:
./mongod --auth --replSet <name> --dbpath /mypath/ --port <port> --keyFile /mypath/mongodb-keyfile --oplogSize 64 --smallfiles

And finally run the mongo-connector:
mongo-connector --auto-commit-interval=0 -m mongodb://host:port/db -t http://host:port/solr/<core> -d /solr_doc_manager.py -n <db>.<collection> -o /path/config.txt --unique-key=id --admin-username ced --password-file mongodb-keyfile

And the result:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "build/bdist.linux-x86_64/egg/mongo_connector/connector.py", line 283, in run
    main_conn['admin'].authenticate(self.auth_username, self.auth_key)
  File "build/bdist.linux-x86_64/egg/pymongo/database.py", line 902, in authenticate
    self.connection._cache_credentials(self.name, credentials)
  File "build/bdist.linux-x86_64/egg/pymongo/mongo_client.py", line 459, in _cache_credentials
    auth.authenticate(credentials, sock_info, self.__simple_command)
  File "build/bdist.linux-x86_64/egg/pymongo/auth.py", line 243, in authenticate
    auth_func(credentials[1:], sock_info, cmd_func)
  File "build/bdist.linux-x86_64/egg/pymongo/auth.py", line 222, in _authenticate_mongo_cr
    cmd_func(sock_info, source, query)
  File "build/bdist.linux-x86_64/egg/pymongo/mongo_client.py", line 693, in __simple_command
    helpers._check_command_response(response, None, msg)
  File "build/bdist.linux-x86_64/egg/pymongo/helpers.py", line 178, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
OperationFailure: command SON([('authenticate', 1), ('user', u'ced'), ('nonce', u'2a8ca040bcd37bf0'), ('key', u'6d500a5cadf173cd2930bb9c4fa92b44')]) failed: auth failed

Thanks

**Comment by lovett89** [comment]
@crashbtz

The `--password-file` option should take a file that contains the user's password. It shouldn't be confused with the `--keyFile` option that mongod takes, which is the key that nodes within a cluster use to authenticate to each other. For example, if I had a user `user` with password `password`, I'd do:

    # Don't print trailing newline
    /bin/echo -n password > passwordfile
    mongo-connector -a user -f passwordfile ...

I'm sorry if the [usage with authentication](https://github.com/10gen-labs/mongo-connector/wiki/Usage-with-Authentication) documentation was vague on this. I'll update it to make it clearer.

**Comment by crashbtz** [comment]
Thanks for the response, it's more clearly.
And is there any specials characters which need to be avoid or some encodage specification?
Because I still have "failed: auth failed"

I did like you told me:

    echo -n 'yF2165AG[d7[!DglL=;R' > keyfile

I have to use the apostrophe ortherwise I have "-bash: !DglL=: event not found"
And then:

    mongo-connector --auto-commit-interval=0 -m mongodb://<hostMongo>:<portMongo>/<db> -t http://<host>:<port>/solr/<core> -d /path/solr_doc_manager.py -n <db>.<collection> -o /path/config.txt --unique-key=id -v --admin-username R2owner --password-file keyfile

And the log:

    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
      File "build/bdist.linux-x86_64/egg/mongo_connector/connector.py", line 283, in run
    main_conn['admin'].authenticate(self.auth_username, self.auth_key)
      File "build/bdist.linux-x86_64/egg/pymongo/database.py", line 902, in authenticate
    self.connection._cache_credentials(self.name, credentials)
      File "build/bdist.linux-x86_64/egg/pymongo/mongo_client.py", line 459, in _cache_credentials
    auth.authenticate(credentials, sock_info, self.__simple_command)
      File "build/bdist.linux-x86_64/egg/pymongo/auth.py", line 243, in authenticate
    auth_func(credentials[1:], sock_info, cmd_func)
      File "build/bdist.linux-x86_64/egg/pymongo/auth.py", line 222, in _authenticate_mongo_cr
    cmd_func(sock_info, source, query)
      File "build/bdist.linux-x86_64/egg/pymongo/mongo_client.py", line 693, in __simple_command
    helpers._check_command_response(response, None, msg)
      File "build/bdist.linux-x86_64/egg/pymongo/helpers.py", line 178, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
    OperationFailure: command SON([('authenticate', 1), ('user', u'R2owner'), ('nonce', u'd785fa1361419512'), ('key', u'560433e7e6fd6ca9b60cb61797cdf558')]) failed: auth failed

But the connection to the database works fine:

    ./mongo -u R2owner -p 'yF2165AG[d7[!DglL=;R' <hostMongo>:<portMongo>/<db>

And this one works to:

    mongo-connector --auto-commit-interval=0 -m mongodb://R2owner:'yF2165AG[d7[!DglL=;R'@<hostMongo>:<portMongo>/<db> -t http://<host>:<port>/solr/<core> -d /path/solr_doc_manager.py -n <db>.<collection> -o /path/config.txt --unique-key=id

Thanks

**Comment by crashbtz** [comment]
Ok, I finally make it works.
I was looking in the connector.py and understood the user has to belong to the "admin" database and my DBA create my user in the database which we use in the project.

So I made my test and create a user in the admin database and that works.

Thank you
