### ISSUE TITLE
mongodb_meta (elasticsearch) index never gets created and update failed

### ISSUE THREAD

**Issue by TissonMathew** [10gen-labs/mongo-connector#214]
I'm trying to index a single MongoDB collection called catalog.summary to Elasticsearch, this collection has just one document in it. I'm using mongo-connector 2.5.3 (upgraded to the latest). 

Here's what I did. 

1) Stopped mongo-connector
2) Deleted oplog.timestamp file
3) Deleted “catalog” elasticsearch index 
4) Created “catalog” elasticsearch index with mappings

curl -u xyz: -XPUT https://xxxx.com -d '{"settings" : {"number_of_shards" : 1 }, "mappings" : {"summary" : { "properties" : {"RetailerName" : { "type" : "string", "index" : "not_analyzed" }, "BrandName" : { "type" : "string", "index" : "not_analyzed" }, "Categories" : { "type" : "string", "index" : "not_analyzed" } } } } }'

5) Started mongo-connector 

sudo mongo-connector -m xyz.mongolab.com:64697 -t https://xyz:@xxxx.com -d elastic_doc_manager -n catalog.summary --admin-username oplog-reader --password abc123 --auto-commit-interval=60

6) Updated the MongoDB document (catalog.summary) but mongo-connector fails to update the elasticsearch index. 

I'm using hosted MongoDB cluster from MongoLab. I have changed the server names and other private info.

This is my log from mongo-connector. 

The error above seems to be complaining that the document I'm updating doesn’t exist in elasticsearch index. I'm assuming at start up mongo-connector see if the destination is empty it should do a collection dump but i don't see that's happening from the log. Also, I wonder why it's not creating mongodb_meta index. 

[ec2-user@ip-172-16-0-161 ~]$ cat mongo-connector.log
2015-02-25 17:54:28,995 [INFO] mongo_connector.connector:988 - Beginning Mongo Connector
2015-02-25 17:54:28,995 [INFO] mongo_connector.connector:116 - MongoConnector: Can't find oplog.timestamp, attempting to create an empty progress log
2015-02-25 17:54:29,330 [INFO] mongo_connector.connector:222 - MongoConnector: Empty oplog progress file.
2015-02-25 17:54:29,763 [INFO] mongo_connector.oplog_manager:87 - OplogThread: Initializing oplog thread
2015-02-25 17:54:29,835 [INFO] mongo_connector.connector:294 - MongoConnector: Starting connection thread MongoClient([u'xyz.mongolab.com:64696', u'xyz.mongolab.com:64697'])
2015-02-25 17:55:29,000 [INFO] elasticsearch:62 - POST http://xxxx:443/_refresh [status:200 request:0.005s]
2015-02-25 17:55:29,000 [INFO] elasticsearch.trace:72 - curl -XPOST 'http://localhost:9200/_refresh?pretty' -d ''
2015-02-25 17:55:34,610 [INFO] elasticsearch:62 - POST http://xxxx:443/_refresh [status:200 request:0.005s]
2015-02-25 17:55:34,610 [INFO] elasticsearch.trace:72 - curl -XPOST 'http://localhost:9200/_refresh?pretty' -d ''
2015-02-25 17:55:34,616 [WARNING] elasticsearch:81 - GET /catalog/summary/54e7c8a9bfede101744e4adb [status:404 request:0.005s]
2015-02-25 17:55:34,616 [ERROR] mongo_connector.oplog_manager:278 - Unable to process oplog document {u'h': 5014242376426869494L, u'ts': Timestamp(1424886903, 1), u'o': {u'ItemId': 39, u'SeoKeywords': u'LectroFan - Fan Sound and White Noise Machine, White, Black Colors', u'RetailerName': u'Amazon', u'ImageUrl': u'http://ecx.images-amazon.com/images/I/81DBEz5lnjL._SL1500_.jpg', u'BrandName': u'LectroSound', u'AffiliateMarketingVerbs': [u'Fan Sound', u'White Noise'], u'SeoDescription': u'LectroFan - Fan Sound and White Noise Machine, White', u'ListPrice': 64.950000000000003, u'Description': u"<p><b>LectroFan's</b> compact size makes it perfect for baby nurseries, day care centers, college dorms, apartments - or any sleep environment where unwanted, disturbing, or intrusive noises are a problem. The <b>LectroFan</b> has two ways to reduce unwanted noises, either fan sounds or white noise sounds. Each has 10 non repeating unique sound variations.</p> <p>Use it in your office or bedroom, or take it with you on your travels. The<b> LectroFan</b> uses a USB cord for power so it can be plugged into most computers if you're on the go. Unlike other sound machines, <b>LectroFan's</b> sounds are dynamically generated, they never repeat. Which means your or your baby's sleep wont be disturbed by the looping of short recordings which makes it one of the best sound therapy products on the market. In addition it has a multi-level volume control so you can adjust to any environment.</p><p>Don't have a baby? That's OK, use it to: <br>-Block out noisy neighbors<br>-Drown out your partner snoring<br>-Reduce tinnitus ringing or hissing<br>-Sound proof a room for studying or reading<br>-Sleep easier during the day<br>-Keep conversations confidential at work or home</p>", u'SellingPrice': 54.950000000000003, u'Properties': [{u'Name': u'ASIN', u'Value': u'B00E6D6LQY'}, {u'Name': u'UPC', u'Value': u'897392002060'}, {u'Name': u'Shipping Weight', u'Value': u'1 pounds'}, {u'Name': u'Product Dimensions', u'Value': u'4.4 x 4.4 x 2.2 inches ; 1 pounds'}], u'Categories': [u'Electronics', u'Fans'], u'Name': u'LectroFan Gold - Fan Sound and White Noise Black Machine, White', u'Summary': u'<ul><li>Small transportable size and great for travel</li><li>Powered using USB. Can be plugged into computer or AC Adapter (included). AC adapter runs on 100 to 240 VAC</li><li>10 non-repeating unique fan sounds &amp; 10 non-repeating unique white noise sounds</li><li>Multilevel adjustable volume and 60 minute sleep timer</li><li>Multi-band parametric EQ speaker compensation</li></ul>', u'CostPrice': 3.1000000000000001, u'ImageAltTag': u'LectroFan - Fan Sound and White Noise Machine, White Color', u'Locale': u'en-Us', u'AffiliateDealTypes': [u'Placement', u'PayPerClick'], u'Currency': None, u'AltTag': u'LectroFan - Fan Sound and White Noise Machine, White', u'SeoTitle': u'LectroFan - Fan Sound and White Noise Machine, White', u'_id': ObjectId('54e7c8a9bfede101744e4adb')}, u'v': 2, u'ns': u'catalog.summary', u'o2': {u'_id': ObjectId('54e7c8a9bfede101744e4adb')}, u'op': u'u'}
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 264, in run
    ns, timestamp)
  File "/usr/lib/python2.6/site-packages/mongo_connector/util.py", line 38, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/lib/python2.6/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 121, in update
    id=u(document_id))
  File "/usr/lib/python2.6/site-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.6/site-packages/elasticsearch/client/__init__.py", line 321, in get
    params=params)
  File "/usr/lib/python2.6/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/http_urllib3.py", line 86, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/base.py", line 102, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
OperationFailed: TransportError(404, u'{"_index":"catalog","_type":"summary","_id":"54e7c8a9bfede101744e4adb","found":false}')
[ec2-user@ip-172-16-0-161 ~]$

**Comment by TissonMathew** [comment]
It was a user permission issue. The database user didn't have oplog privileges.
