### ISSUE TITLE
SOLR Insert/Update Failing, still in Python dictionary form?

### ISSUE THREAD

**Issue by flavouski** [10gen-labs/mongo-connector#216]
When a document is being sent to SOLR (4.10.3) from Mongo (2.6.6) with the Mongo-Connector (2.5.3? I just ran `pip install mongo-connector --upgrade`) it fails to load required fields that I had setup in the schema.xml:
```xml
<field name="metadata.lastModifiedBy" type="string" required="true" indexed="true" stored="true" />
```
<b>Why is the message being sent from Mongo to SOLR in Python and not its converted structure?</b>
I saw this was <a href='https://github.com/10gen-labs/mongo-connector/issues/89'>fixed previously</a>, but unsure what I am missing to get a hierarchy structure sent

<b>Error:</b>
2015-02-28 09:55:37,511 [ERROR] mongo_connector.oplog_manager:278 - Unable to process oplog 
```javascript
document {u'h': 8916194018810643010L, u'ts': Timestamp(1425138937, 3), u'o': {'_id': u'634be1ff-bf24-679e-9da6-08641e3040bb', '_ts': 6120925126671204355,
    u'attributes': {u'headline': u'ABBA', u'bodyCopy': u'cups', u'name': u'CELL_20150228_bees', u'disclaimer': u'quote', u'nameCaseInsensitive': u'cell_20150228_bees'}, 'ns': u'test.content.history', u'_class': u'org.Asset', 
    u'metadata': {u'status': u'Draft', u'parentFolder': u'/', u'contentType': u'//messaging', u'created': datetime.datetime(2015, 2, 27, 17, 31, 32, 951000), u'lastModified': datetime.datetime(2015, 2, 28, 15, 55, 37, 467000), u'key': u'6dadfb07-88d4-4e4b-84ec-52b1be340734', u'lastModifiedBy': {u'_id': u'publisher', u'_class': u'org.User'}, u'version': u'13', u'createdBy': {u'_id': u'publisher', u'_class': u'org.User'}, u'path': u'/CELL_20150228_bees'}}, 
u'v': 2, u'ns': u'test.content.history', u'op': u'i'
}
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 257, in run
    docman.upsert(doc, ns, timestamp)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 38, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/doc_managers/solr_doc_manager.py", line 260, in upsert
    commit=False)
  File "/usr/local/lib/python2.7/site-packages/pysolr.py", line 799, in add
    return self._update(m, commit=commit, softCommit=softCommit, waitFlush=waitFlush, waitSearcher=waitSearcher)
  File "/usr/local/lib/python2.7/site-packages/pysolr.py", line 390, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "/usr/local/lib/python2.7/site-packages/pysolr.py", line 322, in _send_request
    raise SolrError(error_message)
OperationFailed: [Reason: None]

```xml
<response>
    <lst name="responseHeader">
        <int name="status">400</int>
        <int name="QTime">1</int>
    </lst>
    <lst name="error">
        <str name="msg">[doc=634be1ff-bf24-679e-9da6-08641e3040bb] missing required field: metadata.lastModifiedBy</str>
        <int name="code">400</int>
    </lst>
</response>
```

**Comment by flavouski** [comment]
Just realized I was missing: metadata.lastModifiedBy._id

Nevermind.
