### ISSUE TITLE
Update SOLR Fails

### ISSUE THREAD

**Issue by flavouski** [10gen-labs/mongo-connector#218]
Whenever I do an update from Mongo (2.6.6)  to SOLR(4.10.3) using the Mongo-Connector (2.0.1) I get a 2015-03-03 09:39:04,553 [ERROR] mongo_connector.util:87 - Fatal Exception:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/oplog_manager.py", line 264, in run
    ns, timestamp)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/doc_managers/solr_doc_manager.py", line 238, in update
    doc.pop('ns')
KeyError: 'ns'
```

Insert works fine and SOLR doesn't throw any exception in their logs for an update.

Some of the structure in the schema I have:
```xml
   <field name="_version_" type="long" indexed="true" stored="true"/>
   <field name="_root_" type="string" indexed="true" stored="false"/>

   <!-- Custom Fields -->
   <field name="_id"                            type="string" indexed="true" stored="true" required="true" multiValued="false" /> 
   <field name="attributes.name"                type="string" indexed="true" stored="true" required="true" multiValued="false" /> 
   <field name="metadata.lastModifiedBy._id"    type="string" indexed="true" stored="true" required="true" multiValued="false" /> 
   <field name="metadata.createdBy._id"         type="string" indexed="true" stored="true" required="true" multiValued="false" /> 
   <field name="metadata.contentType"           type="string" indexed="true" stored="true" required="true" multiValued="false" /> 
   <field name="metadata.status"                type="string" indexed="true" stored="true" required="true" multiValued="false" /> 
   
   <field name="metadata.lastModified"          type="tdate" indexed="true" stored="true" required="true" multiValued="false" /> 
   <field name="metadata.created"               type="tdate" indexed="true" stored="true" required="true" multiValued="false" /> 
   
   <!-- TODO delete when no longer needed -->
   <field name="metadata.path"                  type="string" indexed="false" stored="true" required="true" multiValued="false" />      
   <field name="metadata.parentFolder"          type="string" indexed="false" stored="true" required="true" multiValued="false" />            

   <field name="textSearch"                     type="text_general"  indexed="true" stored="true" required="true" multiValued="true" />

   <dynamicField name="metadata.allowedUser*"   type="string"        indexed="true" stored="true" required="false" multiValued="true" />

   <copyField source="attributes.*" dest="textSearch"/>
   <!-- We ignore all fields that we don't care about -->
   <dynamicField name="*" type="ignored" multiValued="true" />
   
   <uniqueKey>_id</uniqueKey>
```

The document looks like this in MongoDB: (_id actually matches metadata.key):
```javascript
{
  "_id": BinData(3, "KExrO7uNDzinZYwNLKRyvQ=="),
  "_class": "org.asset.domain.Asset",
  "metadata": {
    "contentType": "//messaging",
    "path": "/AUD_20150304_VV",
    "parentFolder": "/",
    "key": "380f8dbb-3b6b-4c28-bd72-a42c0d8c65a7",
    "version": "1",
    "createdBy": {
      "_id": "publisher",
      "_class": "org.common.User"
    },
    "created": new Date(1425397092185),
    "lastModifiedBy": {
      "_id": "publisher",
      "_class": "org.common.User"
    },
    "lastModified": new Date(1425397092185),
    "status": "Draft"
  },
  "attributes": {
    "name": "SomeName",
    "headline": "Qualm",
    "bodyCopy": "Oranges",
    "nameCaseInsensitive": "somename"
  }
}
```

**Comment by llvtt** [comment]
Do you have field definitions for `ns` and `_ts` anywhere in your schema definition? Mongo Connector needs these two fields to store metadata in each document. Something like this will work:

     <field name="_ts" type="long" indexed="true" stored="true" />
     <field name="ns" type="string" indexed="true" stored="true"/>

**Comment by flavouski** [comment]
Oh, yeah I was wondering what the line reference of pop for ns/ts and didn't realize that was something Mongo was storing behind the scenes (and was hidden by MongoHub browser).  Thanks!

**Comment by llvtt** [comment]
No problem! I'll make this clearer in the wiki.
