### ISSUE TITLE
Always getting Invalid Configuration - Could not import elasticsearch doc manager errors...

### ISSUE THREAD

**Issue by bdesilva** [10gen-labs/mongo-connector#219]
Hi, I have mongo-connector setup on a separate server and five elastic search servers (all on the same network) and a mongo replica set on a separate server and I'm trying to index all my Mongo data. The Mongo replica set is using the new wired tiger compression feature and I'm using this command line interface to start the sync between mongo-connector, mongo, and elasticsearch:

mongo-connector -m mongo-connector-server:27017 -t elastic-search-servers:9200 --continue-on-error true -d /usr/lib/python2.6/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py

And I keep getting this error:

No handlers could be found for logger "mongo_connector.util"
Traceback (most recent call last):
  File "/usr/bin/mongo-connector", line 9, in <module>
    load_entry_point('mongo-connector==2.0.1', 'console_scripts', 'mongo-connector')()
  File "/usr/lib/python2.6/site-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/mongo_connector/connector.py", line 950, in main
    conf.parse_args()
  File "/usr/lib/python2.6/site-packages/mongo_connector/config.py", line 114, in parse_args
    option, dict((k, values.get(k)) for k in option.cli_names))
  File "/usr/lib/python2.6/site-packages/mongo_connector/connector.py", line 778, in apply_doc_managers
    module = import_dm_by_name(dm['docManager'])
  File "/usr/lib/python2.6/site-packages/mongo_connector/connector.py", line 768, in import_dm_by_name
    "Could not import %s." % full_name)
mongo_connector.errors.InvalidConfiguration: Could not import mongo_connector.doc_managers./usr/lib/python2.6/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py.

Can someone please help me with this?

Thanks,
Ben.

**Comment by llvtt** [comment]
In Mongo Connector 2.0.1, you only need to pass the name of the doc manager, not the full path to the Python source. See [configuration options](https://github.com/10gen-labs/mongo-connector/wiki/Configuration%20Options#docmanagersindexdocmanager).

**Comment by bdesilva** [comment]
Oh okay cool, so I've done that and all it says is: Logging to mongo-connector.log. whereas before I could see the data being ported. Is this a new feature?
Also, while monitoring Elasticsearch, I do see the data being indexed, however on my indices table in elasticsearch, I only see the database name, whereas with mongo-connector before I would see database.collection_name. Why is that?
Thanks again.

**Comment by llvtt** [comment]
Yep, Mongo Connector creates a log file by default now. You can still see all the data as it's being sent if you tail the log, though.

In Mongo Connector 2, the MongoDB database name is used as the index name, and the collection name is used as the mapping type in Elasticsearch. In 1.0, "<database>.<collection>" was used as the index name, and the mapping type was always "string".

**Comment by bdesilva** [comment]
Thanks again. We are doing a huge data port, approximately 700GB of data. What would be the best optimization query for the mongo connector? Currently I'm using this query:

mongo-connector -m mongo-connector-server:27017 -t elastic-search-servers:9200 --continue-on-error true -d /usr/lib/python2.6/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py

I've also added a --batch-size 1000 (I'm assuming 1000 documents per bulk index into Elasticsearch), but mongo-connector always crashes. How should I configure mongo-connector to do this properly as it's sitting one a separate server as well?

Thanks,
Ben.

**Comment by llvtt** [comment]
That command won't work with Mongo Connector 2.x, as explained above. Are you using an older version of the connector now? If so, which version?

Can you provide the logs up to the point where Mongo Connector quits?

**Comment by bdesilva** [comment]
Hi, so my log file is as follows:

2015-03-12 08:25:20,275 [INFO] mongo_connector.connector:988 - Beginning Mongo Connector
2015-03-12 08:25:20,276 [INFO] mongo_connector.connector:116 - MongoConnector: Can't find oplog.timestamp, attempting to create an empty progress log
2015-03-12 08:25:20,284 [INFO] mongo_connector.connector:222 - MongoConnector: Empty oplog progress file.
2015-03-12 08:25:20,312 [INFO] mongo_connector.oplog_manager:87 - OplogThread: Initializing oplog thread
2015-03-12 08:25:20,339 [INFO] mongo_connector.connector:294 - MongoConnector: Starting connection thread MongoClient([u'mongo.replicaset1:27017', u'mongo.replicaset2:27017', u'mongo.replicaset3:27017'])
2015-03-12 08:25:48,130 [INFO] urllib3.connectionpool:188 - Starting new HTTP connection (1): elasticsearch.server
2015-03-12 08:25:48,147 [WARNING] elasticsearch:81 - POST http://elasticsearch.server:9200/_bulk [status:N/A request:0.017s]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/http_urllib3.py", line 71, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 575, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/lib/python2.6/site-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 529, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 334, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python2.6/httplib.py", line 914, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.6/httplib.py", line 951, in _send_request
    self.endheaders()
  File "/usr/lib64/python2.6/httplib.py", line 908, in endheaders
    self._send_output()
  File "/usr/lib64/python2.6/httplib.py", line 780, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.6/httplib.py", line 739, in send
    self.connect()
  File "/usr/lib/python2.6/site-packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.6/site-packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.6/site-packages/urllib3/util/connection.py", line 64, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
ProtocolError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2015-03-12 08:25:48,150 [INFO] urllib3.connectionpool:188 - Starting new HTTP connection (2): elasticsearch.server
2015-03-12 08:25:48,168 [WARNING] elasticsearch:81 - POST http://elasticsearch.server:9200/_bulk [status:N/A request:0.018s]
Traceback (most recent call last):

  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/http_urllib3.py", line 71, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 575, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/lib/python2.6/site-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 529, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 334, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python2.6/httplib.py", line 914, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.6/httplib.py", line 951, in _send_request
    self.endheaders()
  File "/usr/lib64/python2.6/httplib.py", line 908, in endheaders
    self._send_output()
  File "/usr/lib64/python2.6/httplib.py", line 780, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.6/httplib.py", line 739, in send
    self.connect()
  File "/usr/lib/python2.6/site-packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.6/site-packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
"mongo-connector.log" 2952362L, 212657637C




2015-03-12 08:50:44,756 [WARNING] elasticsearch:81 - PUT http://elasticsearch.server:9200/tphub/users/0481d0f0-5437-439c-98ab-a5ab1ed9c1cd?refresh=false [status:N/A request:0.012s]
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/http_urllib3.py", line 71, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 575, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/lib/python2.6/site-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 529, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.6/site-packages/urllib3/connectionpool.py", line 334, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python2.6/httplib.py", line 914, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.6/httplib.py", line 951, in _send_request
    self.endheaders()
  File "/usr/lib64/python2.6/httplib.py", line 908, in endheaders
    self._send_output()
  File "/usr/lib64/python2.6/httplib.py", line 780, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.6/httplib.py", line 739, in send
    self.connect()
  File "/usr/lib/python2.6/site-packages/urllib3/connection.py", line 155, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.6/site-packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.6/site-packages/urllib3/util/connection.py", line 64, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
ProtocolError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2015-03-12 08:50:44,757 [ERROR] mongo_connector.oplog_manager:462 - Could not upsert document: {u'lastModifiedDate': datetime.datetime(2014, 8, 22, 15, 44, 4), u'externalIds': [{u'id': u'April', u'provider': u'leadmx.com'}], u'createDate': datetime.datetime(2014, 8, 22, 15, 44, 4), u'v': 1}
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mongo_connector/oplog_manager.py", line 457, in upsert_each
    dm.upsert(doc, mapped_ns, long_ts)
  File "/usr/lib/python2.6/site-packages/mongo_connector/util.py", line 38, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/lib/python2.6/site-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 142, in upsert
    refresh=(self.auto_commit_interval == 0))
  File "/usr/lib/python2.6/site-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.6/site-packages/elasticsearch/client/__init__.py", line 256, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/lib/python2.6/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/http_urllib3.py", line 82, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionFailed: ConnectionError(('Connection aborted.', gaierror(-2, 'Name or service not known'))) caused by: ProtocolError(('Connection aborted.', gaierror(-2, 'Name or service not known')))
2015-03-12 08:50:49,718 [ERROR] mongo_connector.oplog_manager:468 - Failed to upsert 21239 docs

I excluded the middle part but it ends like this.

Please help.

Thanks.

**Comment by llvtt** [comment]
You're using version 2.0 of the connector, so the command you want should look similar to this:

    mongo-connector -m mongohost:mongoport -t elastichost:elasticport -d elastic_doc_manager <other options...>

The `ConnectionError` in the log indicates that Mongo Connector cannot connect to Elasticsearch. Mongo Connector uses the REST interface to Elasticsearch, so you might see if you're able to use `curl` or something similar to send messages to Elasticsearch from the same machine on which `mongo-connector` is running. Also, make sure that you're **not** including `http` in the hostname for Elasticsearch supplied to the `-t` option.

**Comment by bdesilva** [comment]
Thanks that works, however now what I'm finding when I'm telling mongo-connector to index only certain fields using the -i parameter, it indexes it in Elasticsearch under the _source element which is not searchable. How can I properly port over and index only certain items from a certain collection?

This is my parameter used: mongo-connector -m mong_replica_set:27017 -t localhost:9200 -d elastic_doc_manager -n sourcedb.sourcecollection -g newindex.newtype -i includeField

**Comment by llvtt** [comment]
It looks like this has been opened as another issue, #221. Since this issue was about ConfigurationError, which seems to be resolved, I'll close this one and respond on the new issue. Feel free to reopen this if you feel this issue is still separately unresolved.
