### ISSUE TITLE
Problem install

### ISSUE THREAD

**Issue by crashbtz** [10gen-labs/mongo-connector#224]
Hi,
I have a problem to install mongo-connector.
I'm using a Suse 11 and I tried differents versions of python.

Python 3.4: > python3.4 setup.py install

    Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-0.9.7.tar.gz
    Traceback (most recent call last):
      File "setup.py", line 38, in <module>
        from setuptools import setup
    ImportError: No module named 'setuptools'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/users/webmontc/mongo-connector/ez_setup.py", line 114, in use_setuptools
        import pkg_resources
    ImportError: No module named 'pkg_resources'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "setup.py", line 41, in <module>
        use_setuptools()
      File "/home/users/webmontc/mongo-connector/ez_setup.py", line 116, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/home/users/webmontc/mongo-connector/ez_setup.py", line 100, in _do_download
        to_dir, download_delay)
      File "/home/users/webmontc/mongo-connector/ez_setup.py", line 162, in download_setuptools
        src = urlopen(url)
      File "/usr/local/lib/python3.4/urllib/request.py", line 161, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/local/lib/python3.4/urllib/request.py", line 463, in open
        response = self._open(req, data)
      File "/usr/local/lib/python3.4/urllib/request.py", line 486, in _open
        'unknown_open', req)
      File "/usr/local/lib/python3.4/urllib/request.py", line 441, in _call_chain
        result = func(*args)
      File "/usr/local/lib/python3.4/urllib/request.py", line 1252, in unknown_open
        raise URLError('unknown url type: %s' % type)
    urllib.error.URLError: <urlopen error unknown url type: https>
    
Python 2.6: > python2.6 setup.py install

    Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-0.9.7.tar.gz
    Traceback (most recent call last):
      File "setup.py", line 41, in <module>
        use_setuptools()
      File "/home/users/webmontc/mongo-connector/ez_setup.py", line 116, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/home/users/webmontc/mongo-connector/ez_setup.py", line 100, in _do_download
        to_dir, download_delay)
      File "/home/users/webmontc/mongo-connector/ez_setup.py", line 162, in download_setuptools
        src = urlopen(url)
      File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
        return _opener.open(url, data, timeout)
      File "/usr/lib64/python2.6/urllib2.py", line 391, in open
        response = self._open(req, data)
      File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
        '_open', req)
      File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
        result = func(*args)
      File "/usr/lib64/python2.6/urllib2.py", line 1194, in https_open
        return self.do_open(httplib.HTTPSConnection, req)
      File "/usr/lib64/python2.6/urllib2.py", line 1161, in do_open
        raise URLError(err)
    urllib2.URLError: <urlopen error [Errno -2] Name or service not known>

Thanks

**Comment by llvtt** [comment]
The Python 3.4 error message seems to indicate some trouble making a request to an `https` URL. Do you know if your Python has SSL support? Can you confirm that this works in Python 3.4?

    import ssl  # no exception here
    from urllib import request
    print(request.urlopen('https://github.com').read())  # no exception here

**Comment by crashbtz** [comment]
Hi,
Your test doesn't work, it miss some libraries and I don't know how to install all the dependancies cause where I work, they gave us vm with Suse SLES 11.3 with some restrictions and I didn't find any documentation about my problem on Suse.
I wanted to use my own mongo-connector but I gave up and keep using the one which has been installed on the dev server.

Thank you anyway
