### ISSUE TITLE
'Database' object is not callable

### ISSUE THREAD

**Issue by artemryzhov** [10gen-labs/mongo-connector#240]
I can't run mongo-connector.

Logging to mongo-connector.log.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 282, in run
    main_conn.disconnect()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 1050, in __call__
    self.__name, self.__client.__class__.__name__))
TypeError: 'Database' object is not callable. If you meant to call the 'disconnect' method on a 'MongoClient' object it is failing because no such method exists.

**Comment by behackett** [comment]
If you just installed, this is likely due to the release of PyMongo 3.0 yesterday. mongo-connector's setup.py needs to be updated to limit the version of PyMongo it requires to < 3.0.

You can solve this problem by explicitly installing PyMongo 2.8:

pip install pymongo==2.8

or

easy_install pymongo==2.8

@llvtt can you do a patch release changing install_requires?

**Comment by artemryzhov** [comment]
Thank you very much! It works! :)
