### ISSUE TITLE
SolrError(error_message) OperationFailed: [Reason: None]

### ISSUE THREAD

**Issue by ishare** [10gen-labs/mongo-connector#242]
I use solrcloud, and my schema.xml definition contains:
`<field name="name"      type="string"   indexed="true"  stored="true"  multiValued="false" />`
`<field name="age"      type="int"   indexed="true"  stored="true" />`

I exec  `db.c.insert({"name":"ddd", "age": 1})` in mongodb, using mongo-connector, I found the follow errors, could you help me solve it?
If I remove `"age": 1`, mongo-connector works, no error occur.

2015-04-16 20:57:03,853 [DEBUG] pysolr:783 - Starting to build add request...
2015-04-16 20:57:03,853 [DEBUG] pysolr:798 - Built add request of 1 docs in 0.00 seconds.
2015-04-16 20:57:03,853 [DEBUG] pysolr:286 - Starting request to 'http://localhost:8983/solr/xx_shard1_replica1/update/?commit=false' (post) with body 'u'<add><do'...
2015-04-16 20:57:03,910 [DEBUG] requests.packages.urllib3.connectionpool:383 - "POST /solr/xx_shard1_replica1/update/?commit=false HTTP/1.1" 400 None
2015-04-16 20:57:03,910 [INFO] pysolr:316 - Finished 'http://localhost:8983/solr/xx_shard1_replica1/update/?commit=false' (post) with body 'u'<add><do' in 0.057 seconds.
2015-04-16 20:57:03,911 [ERROR] pysolr:321 - [Reason: None]
<response><lst name="responseHeader"><int name="status">400</int><int name="QTime">52</int></lst><lst name="error"><str name="msg">Bad Requestrequest: http://192.168.83.26:8983/solr/xx_shard1_replica2/update?update.distrib=TOLEADER&distrib.from=http%3A%2F%2F192.168.83.26%3A8983%2Fsolr%2Fxx_shard1_replica1%2F&wt=javabin&version=2</str><int name="code">400</int></lst></response>
2015-04-16 20:57:03,911 [ERROR] mongo_connector.oplog_manager:278 - Unable to process oplog document {u'h': -7001697401628939824L, u'ts': Timestamp(1429189023, 1), u'o': {u'apartment': u'xxx', u'name': u'ddd', u'age': 1.0, '_ts': 6138320113587191809, 'ns': u'test.c', u'job': u'engineer', u'dekb': u'aaa', '_id': u'552fb19fbb5e201d6141a027'}, u'v': 2, u'ns': u'test.c', u'op': u'i'}
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 257, in run
    docman.upsert(doc, ns, timestamp)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/util.py", line 38, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mongo_connector-2.1.dev0-py2.7.egg/mongo_connector/doc_managers/solr_doc_manager.py", line 268, in upsert
    commit=False)
  File "build/bdist.macosx-10.9-intel/egg/pysolr.py", line 799, in add
    return self._update(m, commit=commit, softCommit=softCommit, waitFlush=waitFlush, waitSearcher=waitSearcher)
  File "build/bdist.macosx-10.9-intel/egg/pysolr.py", line 390, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "build/bdist.macosx-10.9-intel/egg/pysolr.py", line 322, in _send_request
    raise SolrError(error_message)
OperationFailed: [Reason: None]
<response><lst name="responseHeader"><int name="status">400</int><int name="QTime">52</int></lst><lst name="error"><str name="msg">Bad Requestrequest: http://192.168.83.26:8983/solr/xx_shard1_replica2/update?update.distrib=TOLEADER&distrib.from=http%3A%2F%2F192.168.83.26%3A8983%2Fsolr%2Fxx_shard1_replica1%2F&wt=javabin&version=2</str><int name="code">400</int></lst></response>
2015-04-16 20:57:03,912 [DEBUG] mongo_connector.oplog_manager:288 - OplogThread: Documents removed: 0, inserted: 0, updated: 0 so far
2015-04-16 20:57:03,912 [DEBUG] mongo_connector.oplog_manager:290 - OplogThread: Doc is processed.

**Comment by llvtt** [comment]
I have tried to reproduce this, but haven't been successful yet. Can you please provide:

1. The command used to run `mongo-connector`
2. Log output from Solr itself.

Thanks.

**Comment by ishare** [comment]
1. mongo-connector -m localhost:27017 -t http://localhost:8983/solr/xx_shard1_replica1 -d solr_doc_manager -v

2. It seems you don't parse int sending to solr, the following is the solr error log.

INFO  - 2015-04-17 02:25:08.163; [xx shard2 core_node1 xx_shard2_replica2] org.apache.solr.update.processor.LogUpdateProcessor; [xx_shard2_replica2] webapp=/solr path=/update params={update.distrib=TOLEADER&distrib.from=http://192.168.83.26:7574/solr/xx_shard1_replica1/&wt=javabin&version=2} {} 0 1
ERROR - 2015-04-17 02:25:08.164; [xx shard2 core_node1 xx_shard2_replica2] org.apache.solr.common.SolrException; org.apache.solr.common.SolrException: ERROR: [doc=55306f04bb5e201d6141a02e] Error adding field 'age'='11.0' msg=For input string: "11.0"
	at org.apache.solr.update.DocumentBuilder.toDocument(DocumentBuilder.java:176)
	at org.apache.solr.update.AddUpdateCommand.getLuceneDocument(AddUpdateCommand.java:78)
	at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:237)
	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:163)
	at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:69)
	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:51)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:947)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:1102)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:703)
	at org.apache.solr.update.processor.LogUpdateProcessor.processAdd(LogUpdateProcessorFactory.java:104)
	at org.apache.solr.handler.loader.JavabinLoader$1.update(JavabinLoader.java:96)
	at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$1.readOuterMostDocIterator(JavaBinUpdateRequestCodec.java:166)
	at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$1.readIterator(JavaBinUpdateRequestCodec.java:136)
	at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:225)
	at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$1.readNamedList(JavaBinUpdateRequestCodec.java:121)
	at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:190)
	at org.apache.solr.common.util.JavaBinCodec.unmarshal(JavaBinCodec.java:116)
	at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec.unmarshal(JavaBinUpdateRequestCodec.java:173)
	at org.apache.solr.handler.loader.JavabinLoader.parseAndLoadDocs(JavabinLoader.java:106)
	at org.apache.solr.handler.loader.JavabinLoader.load(JavabinLoader.java:58)
	at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:103)
	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:74)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:143)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:1984)
	at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:829)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:446)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:220)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:368)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:953)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1014)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:953)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
	at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "11.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.apache.solr.schema.TrieField.createField(TrieField.java:631)
	at org.apache.solr.schema.TrieField.createFields(TrieField.java:694)
	at org.apache.solr.update.DocumentBuilder.addField(DocumentBuilder.java:48)
	at org.apache.solr.update.DocumentBuilder.toDocument(DocumentBuilder.java:123)
	... 51 more

**Comment by llvtt** [comment]
Are you using the Mongo shell to insert the document? In the shell, a number like `"age": 1` is actually a float, not an int, and it's probably conflicting with your schema definition of

     <field name="age" type="int" indexed="true" stored="true" />

Try doing

     db.c.insert({"name":"ddd", "age": NumberInt(1)})

in the shell, or changing the type of `age` to `float` in schema.xml.

**Comment by llvtt** [comment]
Any update on this? May I close this issue?
