### ISSUE TITLE
Initial dump no performed with wiredTiger

### ISSUE THREAD

**Issue by heichwald** [10gen-labs/mongo-connector#244]
Ok, so this one looks like a tricky one because it does not reproduce for me on all systems:
So this is not an issue and works properly on my Mac or on Ubuntu (python 2.7) but does not work on my work servers:
CentOS release 6.6 (Final) 64bits
python 2.6.6

In all cases (works or not) it was run with: 
Mongo 3.0.1
Mongo-connector 2.0.3

The issue only appears with wiredtiger.

Steps I did were:
Delete the mongo data files in /var/lib/mongo
Delete previous logs and oplog files
Starting mongo -1 node only- and configure it as a replica set with rs.initiate()

```
systemLog:
   destination: file
   path: "/var/log/mongo/mongod.log"
   logAppend: true

storage:
   dbPath: "/var/lib/mongo"
   #engine:  mmapv1 
   engine: wiredTiger
   journal:
      enabled: true
processManagement:
   fork: true
   pidFilePath: "/var/run/mongodb/mongod.pid"
net:
   bindIp: 0.0.0.0
   port: 27017
replication:
   replSetName: rs1

```

```
rs1:PRIMARY> rs.status()
{
	"set" : "rs1",
	"date" : ISODate("2015-04-22T20:06:56.171Z"),
	"myState" : 1,
	"members" : [
		{
			"_id" : 0,
			"name" : "mongo01:27017",
			"health" : 1,
			"state" : 1,
			"stateStr" : "PRIMARY",
			"uptime" : 4610,
			"optime" : Timestamp(1429732996, 1),
			"optimeDate" : ISODate("2015-04-22T20:03:16Z"),
			"electionTime" : Timestamp(1429728658, 2),
			"electionDate" : ISODate("2015-04-22T18:50:58Z"),
			"configVersion" : 1,
			"self" : true
		}
	],
	"ok" : 1
}
```

mongorestore from a dump I took previously
When running with mmapv1 engine, mongo-connector runs fine.

When I redo the steps and change the engine, then it looks like mongo-connector does not perform the initial dump and fails -see below-

Any idea which could cause this behaviour?

Thanks

Command to run mongo-connector:
```
/usr/bin/mongo-connector --no-dump false --main mongo01.qa.nymetro.com --verbose 3 --target-url http://elasticsearch01.qa.nymetro.com:9200 --namespace-set assets.images --dest-namespace-set assets_v1.images --doc-manager elastic_doc_manager_nymag  --tz-aware true --logfile /var/log/mongo-connector/log_image_elastic.log --logfile-backups 2 --oplog-ts /var/mongo-connector/oplog_image_elastic.txt > /var/log/mongo-connector/run_image_elastic.log  2>&1 &
```

```
2015-04-22 15:07:43,278 [INFO] mongo_connector.connector:1001 - Beginning Mongo Connector
2015-04-22 15:07:43,279 [WARNING] mongo_connector.connector:116 - MongoConnector: Can't find /var/mongo-connector/oplog_image_elastic_2015-04-22_15-07-42.txt, attempting to create an empty progress log
2015-04-22 15:07:43,286 [INFO] mongo_connector.connector:223 - MongoConnector: Empty oplog progress file.
2015-04-22 15:07:43,294 [INFO] mongo_connector.oplog_manager:87 - OplogThread: Initializing oplog thread
2015-04-22 15:07:43,297 [INFO] mongo_connector.connector:295 - MongoConnector: Starting connection thread MongoClient('mongo01.qa.nymetro.com', 27017)
2015-04-22 15:07:43,298 [DEBUG] mongo_connector.oplog_manager:154 - OplogThread: Run thread started
2015-04-22 15:07:43,298 [DEBUG] mongo_connector.oplog_manager:156 - OplogThread: Getting cursor
2015-04-22 15:07:43,298 [DEBUG] mongo_connector.oplog_manager:656 - OplogThread: reading last checkpoint as None 
2015-04-22 15:07:44,669 [DEBUG] mongo_connector.oplog_manager:568 - OplogThread: Last oplog entry has timestamp 1429729603.
2015-04-22 15:07:44,671 [DEBUG] mongo_connector.oplog_manager:642 - OplogThread: oplog checkpoint updated to Timestamp(1429729603, 1)
2015-04-22 15:07:46,055 [DEBUG] mongo_connector.oplog_manager:174 - OplogThread: Got the cursor, count is 1
2015-04-22 15:07:46,055 [DEBUG] mongo_connector.oplog_manager:181 - OplogThread: about to process new oplog entries
2015-04-22 15:07:46,055 [DEBUG] mongo_connector.oplog_manager:184 - OplogThread: Cursor is still alive and thread is still running.
2015-04-22 15:07:47,167 [DEBUG] mongo_connector.oplog_manager:190 - OplogThread: Iterating through cursor, document number in this cursor is 0
2015-04-22 15:07:47,168 [DEBUG] mongo_connector.oplog_manager:235 - OplogThread: Operation for this entry is u
2015-04-22 15:07:47,168 [DEBUG] urllib3.util.retry:155 - Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2015-04-22 15:07:47,169 [INFO] urllib3.connectionpool:188 - Starting new HTTP connection (1): 172.20.1.68
2015-04-22 15:07:47,187 [DEBUG] urllib3.connectionpool:362 - "POST /_refresh HTTP/1.1" 200 51
2015-04-22 15:07:47,187 [INFO] elasticsearch:57 - POST http://172.20.1.68:9200/_refresh [status:200 request:0.019s]
2015-04-22 15:07:47,188 [DEBUG] elasticsearch:59 - > None
2015-04-22 15:07:47,188 [DEBUG] elasticsearch:60 - < {"_shards":{"total":36,"successful":26,"failed":0}}
2015-04-22 15:07:47,190 [DEBUG] urllib3.util.retry:155 - Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2015-04-22 15:07:47,193 [DEBUG] urllib3.connectionpool:362 - "GET /assets_v2/images/5214edd5e4b0af2571e32ca3 HTTP/1.1" 404 86
2015-04-22 15:07:47,194 [WARNING] elasticsearch:76 - GET /assets_v2/images/5214edd5e4b0af2571e32ca3 [status:404 request:0.004s]
2015-04-22 15:07:47,194 [INFO] elasticsearch:84 - > None
2015-04-22 15:07:47,194 [ERROR] mongo_connector.doc_managers.elastic_doc_manager_nymag:186 - Error in update
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mongo_connector/doc_managers/elastic_doc_manager_nymag.py", line 177, in update
    id=u(document_id))
  File "/usr/lib/python2.6/site-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.6/site-packages/elasticsearch/client/__init__.py", line 272, in get
    params=params)
  File "/usr/lib/python2.6/site-packages/elasticsearch/transport.py", line 284, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/http_urllib3.py", line 55, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.6/site-packages/elasticsearch/connection/base.py", line 97, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
NotFoundError: TransportError(404, u'{"_index":"assets_v2","_type":"images","_id":"5214edd5e4b0af2571e32ca3","found":false}')
2015-04-22 15:07:47,196 [DEBUG] mongo_connector.oplog_manager:290 - OplogThread: Doc is processed.
2015-04-22 15:07:52,234 [DEBUG] mongo_connector.oplog_manager:302 - OplogThread: updating checkpoint afterprocessing new oplog entries
2015-04-22 15:07:52,234 [DEBUG] mongo_connector.oplog_manager:642 - OplogThread: oplog checkpoint updated to Timestamp(1429729603, 1)
2015-04-22 15:07:52,236 [DEBUG] mongo_connector.oplog_manager:184 - OplogThread: Cursor is still alive and thread is still running.
2015-04-22 15:07:57,278 [DEBUG] mongo_connector.oplog_manager:302 - OplogThread: updating checkpoint afterprocessing new oplog entries
2015-04-22 15:07:57,279 [DEBUG] mongo_connector.oplog_manager:642 - OplogThread: oplog checkpoint updated to Timestamp(1429729603, 1)
2015-04-22 15:07:57,281 [DEBUG] mongo_connector.oplog_manager:184 - OplogThread: Cursor is still alive and thread is still running.
2015-04-22 15:08:02,294 [DEBUG] mongo_connector.oplog_manager:302 - OplogThread: updating checkpoint afterprocessing new oplog entries
2015-04-22 15:08:02,327 [DEBUG] mongo_connector.oplog_manager:642 - OplogThread: oplog checkpoint updated to Timestamp(1429729603, 1)
2015-04-22 15:08:02,328 [DEBUG] mongo_connector.oplog_manager:184 - OplogThread: Cursor is still alive and thread is still running.
2015-04-22 15:08:07,341 [DEBUG] mongo_connector.oplog_manager:302 - OplogThread: updating checkpoint afterprocessing new oplog entries
2015-04-22 15:08:07,342 [DEBUG] mongo_connector.oplog_manager:642 - OplogThread: oplog checkpoint updated to Timestamp(1429729603, 1)
2015-04-22 15:08:07,345 [DEBUG] mongo_connector.oplog_manager:184 - OplogThread: Cursor is still alive and thread is still running.
2015-04-22 15:08:12,360 [DEBUG] mongo_connector.oplog_manager:302 - OplogThread: updating checkpoint afterprocessing new oplog entries
2015-04-22 15:08:12,361 [DEBUG] mongo_connector.oplog_manager:642 - OplogThread: oplog checkpoint updated to Timestamp(1429729603, 1)
2015-04-22 15:08:12,363 [DEBUG] mongo_connector.oplog_manager:184 - OplogThread: Cursor is still alive and thread is still running.
2015-04-22 15:08:17,376 [DEBUG] mongo_connector.oplog_manager:302 - OplogThread: updating checkpoint afterprocessing new oplog entries
2015-04-22 15:08:17,376 [DEBUG] mongo_connector.oplog_manager:642 - OplogThread: oplog checkpoint updated to Timestamp(1429729603, 1)
2015-04-22 15:08:17,377 [DEBUG] mongo_connector.oplog_manager:184 - OplogThread: Cursor is still alive and thread is still running.
2015-04-22 15:08:22,390 [DEBUG] mongo_connector.oplog_manager:302 - OplogThread: updating checkpoint afterprocessing new oplog entries
2015-04-22 15:08:22,390 [DEBUG] mongo_connector.oplog_manager:642 - OplogThread: oplog checkpoint updated to Timestamp(1429729603, 1)
2015-04-22 15:08:22,390 [DEBUG] mongo_connector.oplog_manager:184 - OplogThread: Cursor is still alive and thread is still running.
2015-04-22 15:08:27,403 [DEBUG] mongo_connector.oplog_manager:302 - OplogThread: updating checkpoint afterprocessing new oplog entries
2015-04-22 15:08:27,403 [DEBUG] mongo_connector.oplog_manager:642 - OplogThread: oplog checkpoint updated to Timestamp(1429729603, 1)
2015-04-22 15:08:27,403 [DEBUG] mongo_connector.oplog_manager:184 - OplogThread: Cursor is still alive and thread is still running.
2015-04-22 15:08:32,416 [DEBUG] mongo_connector.oplog_manager:302 - OplogThread: updating checkpoint afterprocessing new oplog entries
2015-04-22 15:08:32,416 [DEBUG] mongo_connector.oplog_manager:642 - OplogThread: oplog checkpoint updated to Timestamp(1429729603, 1)
2015-04-22 15:08:32,417 [DEBUG] mongo_connector.oplog_manager:184 - OplogThread: Cursor is still alive and thread is still running.
2015-04-22 15:08:37,429 [DEBUG] mongo_connector.oplog_manager:302 - OplogThread: updating checkpoint afterprocessing new oplog entries
2015-04-22 15:08:37,429 [DEBUG] mongo_connector.oplog_manager:642 - OplogThread: oplog checkpoint updated to Timestamp(1429729603, 1)
2015-04-22 15:08:37,431 [DEBUG] mongo_connector.oplog_manager:184 - OplogThread: Cursor is still alive and thread is still running.
2015-04-22 15:08:42,445 [DEBUG] mongo_connector.oplog_manager:302 - OplogThread: updating checkpoint afterprocessing new oplog entries
2015-04-22 15:08:42,445 [DEBUG] mongo_connector.oplog_manager:642 - OplogThread: oplog checkpoint updated to Timestamp(1429729603, 1)
2015-04-22 15:08:42,447 [DEBUG] mongo_connector.oplog_manager:184 - OplogThread: Cursor is still alive and thread is still running.
2015-04-22 15:08:47,460 [DEBUG] mongo_connector.oplog_manager:302 - OplogThread: updating checkpoint afterprocessing new oplog entries
2015-04-22 15:08:47,460 [DEBUG] mongo_connector.oplog_manager:642 - OplogThread: oplog checkpoint updated to Timestamp(1429729603, 1)
2015-04-22 15:08:47,462 [DEBUG] mongo_connector.oplog_manager:184 - OplogThread: Cursor is still alive and thread is still running.
2015-04-22 15:08:52,476 [DEBUG] mongo_connector.oplog_manager:302 - OplogThread: updating checkpoint afterprocessing new oplog entries
2015-04-22 15:08:52,476 [DEBUG] mongo_connector.oplog_manager:642 - OplogThread: oplog checkpoint updated to Timestamp(1429729603, 1)
2015-04-22 15:08:52,478 [DEBUG] mongo_connector.oplog_manager:184 - OplogThread: Cursor is still alive and thread is still running.
```

**Comment by llvtt** [comment]
Did you mean to include the `--no-dump` in the command? This option 
doesn't take an argument, so `--no-dump false` doesn't mean "do an 
initial dump". With debug logging enabled, you should see the log 
message "OplogThread: Dumping set of collections ..." before the 
collection dump is attempted.

**Comment by heichwald** [comment]
Indeed you are right.
Thanks a lot
I close this issue as invalid.

**Comment by saml** [comment]
I think it's better if command line argument parser errors out for invalid arguments such as `--no-dump false`.
