### ISSUE TITLE
Error syncing from one monogdb cluster to another

### ISSUE THREAD

**Issue by dharshanr** [10gen-labs/mongo-connector#247]
Logging to mongo-connector.log.
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/site-packages/mongo_connector-2.1.dev0-py2.6.egg/mongo_connector/oplog_manager.py", line 490, in do_dump
    upsert_all(dm)
  File "/usr/local/lib/python2.6/site-packages/mongo_connector-2.1.dev0-py2.6.egg/mongo_connector/oplog_manager.py", line 474, in upsert_all
    dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
  File "/usr/local/lib/python2.6/site-packages/mongo_connector-2.1.dev0-py2.6.egg/mongo_connector/doc_managers/doc_manager_base.py", line 99, in bulk_upsert
    self.upsert(doc, namespace, timestamp)
  File "/usr/local/lib/python2.6/site-packages/mongo_connector-2.1.dev0-py2.6.egg/mongo_connector/util.py", line 38, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.6/site-packages/mongo_connector-2.1.dev0-py2.6.egg/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.6/site-packages/mongo_connector-2.1.dev0-py2.6.egg/mongo_connector/doc_managers/mongo_doc_manager.py", line 143, in upsert
    "ns": namespace
  File "/usr/local/lib64/python2.6/site-packages/pymongo/collection.py", line 288, in save
    manipulate, safe, check_keys=check_keys, **kwargs)
  File "/usr/local/lib64/python2.6/site-packages/pymongo/collection.py", line 551, in update
    docs, check_keys, self.uuid_subtype, client)
  File "/usr/local/lib64/python2.6/site-packages/pymongo/message.py", line 393, in _do_batched_write_command
    results.append((idx_offset, send_message()))
  File "/usr/local/lib64/python2.6/site-packages/pymongo/message.py", line 345, in send_message
    command=True)
  File "/usr/local/lib64/python2.6/site-packages/pymongo/mongo_client.py", line 1131, in _send_message
    rv = self.__check_response_to_last_error(response, command)
  File "/usr/local/lib64/python2.6/site-packages/pymongo/mongo_client.py", line 1049, in __check_response_to_last_error
    helpers._check_command_response(result, self.disconnect)
  File "/usr/local/lib64/python2.6/site-packages/pymongo/helpers.py", line 182, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
OperationFailed: not authorized on __mongo_connector to execute command { update: "calendar.launchusers", updates: [ { q: { _id: ObjectId('5504df6f9bd8dff331b2ad55') }, u: { _id: ObjectId('5504df6f9bd8dff331b2a
d55'), ns: "calendar.launchusers", _ts: 6146937823732695124 }, multi: false, upsert: true } ] }

Here are the permissions I have provided the user I am using on the destination cluster

"_id" : "admin.connectoruser",
"user" : "connectoruser",
"db" : "admin",
"roles" : [
        {
                "role" : "root",
                "db" : "admin"
        },
        {
                "role" : "readWrite",
                "db" : "admin"
        },
        {
                "role" : "readWrite",
                "db" : "local"
        },
        {
                "role" : "readWrite",
                "db" : "calendar"
        }
]

**Comment by dharshanr** [comment]
Also when syncing from one mongo connector to another looks like there is only one set of credentials - so I'm assuming that this user needs to exist on both the source and destination clusters

**Comment by llvtt** [comment]
@dharshanr 
The destination cluster's credentials can only be set through a [connection string](http://docs.mongodb.org/manual/reference/connection-string/) passed into the [`--target-url`](https://github.com/10gen-labs/mongo-connector/wiki/Configuration-Options#docmanagersindextargeturl) option.

The OperationFailure could be related to #248, which I just merged. Could you pull from master and retry?

**Comment by dharshanr** [comment]
Thanks. That did the trick!

**Comment by llvtt** [comment]
Great! May I close this issue then?

**Comment by dharshanr** [comment]
So the connector is running (It is consuming a lot of cpu) but I dont see anything in the log files. This is all I see

2015-05-12 14:32:00,940 [INFO] mongo_connector.connector:1004 - Beginning Mongo Connector
2015-05-12 14:32:00,971 [INFO] mongo_connector.connector:223 - MongoConnector: Empty oplog progress file.
2015-05-12 14:32:00,975 [INFO] mongo_connector.oplog_manager:87 - OplogThread: Initializing oplog thread
2015-05-12 14:32:00,976 [INFO] mongo_connector.connector:295 - MongoConnector: Starting connection thread MongoClient([u'server1:27017', u'server2:27017'])
2015-05-12 14:32:00,976 [DEBUG] mongo_connector.oplog_manager:154 - OplogThread: Run thread started
2015-05-12 14:32:00,977 [DEBUG] mongo_connector.oplog_manager:156 - OplogThread: Getting cursor
2015-05-12 14:32:00,977 [DEBUG] mongo_connector.oplog_manager:656 - OplogThread: reading last checkpoint as None
2015-05-12 14:32:00,977 [DEBUG] mongo_connector.oplog_manager:390 - OplogThread: Dumping set of collections []
2015-05-12 14:32:00,983 [DEBUG] mongo_connector.oplog_manager:568 - OplogThread: Last oplog entry has timestamp 1431441120.
2015-05-12 14:32:00,983 [DEBUG] mongo_connector.oplog_manager:488 - OplogThread: Using bulk upsert function for collection dump

I do see a lot updates happening on the box. How can I confirm that the oplog is being synced? This is the command I used 

/usr/local/bin/mongo-connector -m server1:27017 -t mongodb://admin:<pass>@127.0.0.1:27017 -v -d mongo_doc_manager -a con
nectoruser -p <> --logfile-when=H --logfile-interval=1 --logfile-backups=24

**Comment by llvtt** [comment]
There aren't any log messages that appear during the collection dump. In this phase, mongo-connector is just copying documents that already exist from desired collections over to the other system. When mongo-connector begins syncing the oplog, you'll see a message like "OplogThread: about to process new oplog entries". You can also turn up the [verbosity](https://github.com/10gen-labs/mongo-connector/wiki/Configuration-Options#verbosity) to see even more log messages.

**Comment by dharshanr** [comment]
Hi - it took more than a day to complete the initial import. What write preference is used in the initial dump?

MongoDump/Mongorestore might be a lot faster to do the initial import. Is there is a recommendation on how to use MongoDump/Mongorestore to do the initial import, remember the last processed oplog and then start the mongo-connector from that oplog entry?

**Comment by llvtt** [comment]
@dharshanr You can do:
1. Run `mongorestore`
2. Ensure that *no other applications are writing to MongoDB*.
3. Start running `mongo-connector`. Make sure to add the [`--no-dump`](https://github.com/10gen-labs/mongo-connector/wiki/Configuration-Options#nodump) option.
4. Re-enable applications writing to MongoDB, if there were any.

**Comment by llvtt** [comment]
Closing this issue due to inactivity. Feel free to reopen or create a new issue if you think there's more to discuss.
