### ISSUE TITLE
Mongo permissions needed on the source cluster

### ISSUE THREAD

**Issue by dharshanr** [10gen-labs/mongo-connector#249]
Hi,

I am trying to use mongo-connector to replicate data  from one of my hosted mongodb clusters. The mongo user I am trying to use does not have admin permissions. However it has read/write permissions on the db I am interested in replicating and it has read access to the oplog. 

However this does not seem to be sufficient. What are the auth requirements of user to be used with mongo-connector?

**Comment by llvtt** [comment]
The user needs to be able to do the following:

- List shards (if you're running sharded)
- List databases
- Read the oplog
- Read any databases in the `--namespace-set`. Note that if no namespace set is provided, then the user needs to be able to read any arbitrary database.

**Comment by dharshanr** [comment]
Looks like I don't have the 'List database' permission. Why is this needed if I am passing in the namespace?

**Comment by llvtt** [comment]
Sorry for the confusion. Permission to list database names is only required if you don't provide a namespace set. Can you post the traceback from the authentication error?

**Comment by dharshanr** [comment]
Here you go

Logging to mongo-connector.log.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.6/site-packages/mongo_connector-2.1.dev0-py2.6.egg/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.6/site-packages/mongo_connector-2.1.dev0-py2.6.egg/mongo_connector/connector.py", line 262, in run
    main_conn['admin'].authenticate(self.auth_username, self.auth_key)
  File "/usr/local/lib/python2.6/site-packages/pymongo-2.8.1-py2.6-linux-x86_64.egg/pymongo/database.py", line 982, in authenticate
    self.connection._cache_credentials(self.name, credentials)
  File "/usr/local/lib/python2.6/site-packages/pymongo-2.8.1-py2.6-linux-x86_64.egg/pymongo/mongo_client.py", line 468, in _cache_credentials
    auth.authenticate(credentials, sock_info, self.__simple_command)
  File "/usr/local/lib/python2.6/site-packages/pymongo-2.8.1-py2.6-linux-x86_64.egg/pymongo/auth.py", line 475, in authenticate
    auth_func(credentials[1:], sock_info, cmd_func)
  File "/usr/local/lib/python2.6/site-packages/pymongo-2.8.1-py2.6-linux-x86_64.egg/pymongo/auth.py", line 452, in _authenticate_default
    return _authenticate_mongo_cr(credentials, sock_info, cmd_func)
  File "/usr/local/lib/python2.6/site-packages/pymongo-2.8.1-py2.6-linux-x86_64.egg/pymongo/auth.py", line 445, in _authenticate_mongo_cr
    cmd_func(sock_info, source, query)
  File "/usr/local/lib/python2.6/site-packages/pymongo-2.8.1-py2.6-linux-x86_64.egg/pymongo/mongo_client.py", line 704, in __simple_command
    helpers._check_command_response(response, None, msg)
  File "/usr/local/lib/python2.6/site-packages/pymongo-2.8.1-py2.6-linux-x86_64.egg/pymongo/helpers.py", line 182, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
OperationFailure: command SON([('authenticate', 1), ('user', u'<user>'), ('nonce', u'79b45beac6e84b42'), ('key', u'e0881119faf11158c7981737e7cedc50')
: auth failed

I have replaced the actual user.

**Comment by llvtt** [comment]
This shows that authentication is failing against the admin database. In what database does the user live who may read the oplog? Mongo Connector always authenticates against "admin," since that's the only database where a user can be defined so that they have actions on the [cluster resource](http://docs.mongodb.org/manual/reference/resource-document/#cluster-resource).

**Comment by llvtt** [comment]
Any updates on this?

**Comment by dharshanr** [comment]
Hi,

I was able to get admin permissions on the source databases - so I am no longer hitting this issue. If I don't have admin permission I  was seeing this issue even when the list of db and collections is specified.

**Comment by llvtt** [comment]
Being able to authenticate as a user in the admin database is essential for using mongo-connector with auth. Privileges and roles required to use mongo-connector are now detailed in the wiki: https://github.com/10gen-labs/mongo-connector/wiki/Usage%20with%20Authentication#required-permissions.
