### ISSUE TITLE
Unable to connect Solr and MongoDb

### ISSUE THREAD

**Issue by true-def** [10gen-labs/mongo-connector#260]
I am trying to connect Solr 5.1.0 to Mongodb 3.0.3. I checked that both solr and mongodb are up on respective ports. 

> mongo-connector -m localhost:27217 -t localhost:8983/solr
No handlers could be found for logger "mongo_connector.util"
Traceback (most recent call last):
  File "/usr/local/bin/mongo-connector", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 998, in main
    conf.parse_args()
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/config.py", line 114, in parse_args
    option, dict((k, values.get(k)) for k in option.cli_names))
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/connector.py", line 722, in apply_doc_managers
    "Cannot create a Connector with a target URL"
mongo_connector.errors.InvalidConfiguration: Cannot create a Connector with a target URL but no doc manager.

Any idea if there is a compatibility issue ?

**Comment by behackett** [comment]
You have to specify the solr doc manager with the -d option. Please read the documentation here:

https://github.com/10gen-labs/mongo-connector/wiki/Usage%20with%20Solr
