### ISSUE TITLE
WindowsError: [Error 183] Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by NikolaSimovic** [10gen-labs/mongo-connector#263]
Hello there,

The replica set is up and running at 27017, solr is running at port 8983, I created a core named test, and solr_doc_manager is in the mongo-connector folder, as it should be after the mongo-connector installation.

I tried all I could and followed all the tutorials but I still get this error message when I type the following code:
mongo-connector -m localhost:27017 -t http://localhost:8983/solr/test -d solr_doc_manager
*****
C:\Windows\System32>mongo-connector -m localhost:27017 -t http://localhost:8983/
solr/test -d solr_doc_manager
Logging to mongo-connector.log.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\site-packages\mongo_connector\util.py", line 85, in wrap
ped
    func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\mongo_connector\connector.py", line 308, i
n run
    self.write_oplog_progress()
  File "C:\Python27\lib\site-packages\mongo_connector\connector.py", line 192, i
n write_oplog_progress
    os.rename(self.oplog_checkpoint, backup_file)
WindowsError: [Error 183] Cannot create a file when that file already exists
***
Could you please provide any help?

**Comment by llvtt** [comment]
Looks like the backup oplog progress file already exists for some reason. I can think of a couple reasons this could have occurred:
- Running several instances of `mongo-connector` that have the same `--oplog-ts` (or it isn't set on any one of them).
- `mongo-connector` was shut down ungracefully.

Do either of these situations apply to you? If you're just trying out the connector right now, you can just delete the file called "oplog.timestamp.backup," and that should fix your problem. Otherwise, I can advise you in how to try recovering your progress.

**Comment by NikolaSimovic** [comment]
I try to run only one mongo connector.
How can I check if it shut down ungracefully? I think it wasn't even up in the first place.

I deleted the oplog.timestamp.backup file, and now i get this error.
****
C:\Windows\System32>mongo-connector -m localhost:27017 -t http://localhost:8983/
solr -d solr_doc_manager
No handlers could be found for logger "mongo_connector.util"
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\mongo-connector.exe\__main__.py", line 9, in <module
>
  File "C:\Python27\lib\site-packages\mongo_connector\util.py", line 85, in wrap
ped
    func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\mongo_connector\connector.py", line 1000,
in main
    conf.parse_args()
  File "C:\Python27\lib\site-packages\mongo_connector\config.py", line 114, in p
arse_args
    option, dict((k, values.get(k)) for k in option.cli_names))
  File "C:\Python27\lib\site-packages\mongo_connector\connector.py", line 791, i
n apply_doc_managers
    dm_instances.append(module.DocManager(target_url, **kwargs))
  File "C:\Python27\lib\site-packages\mongo_connector\doc_managers\solr_doc_mana
ger.py", line 76, in __init__
    self._build_fields()
  File "C:\Python27\lib\site-packages\mongo_connector\util.py", line 38, in wrap
ped
    reraise(new_type, exc_value, exc_tb)
  File "C:\Python27\lib\site-packages\mongo_connector\util.py", line 32, in wrap
ped
    return f(*args, **kwargs)
  File "C:\Python27\lib\site-packages\mongo_connector\doc_managers\solr_doc_mana
ger.py", line 92, in _build_fields
    declared_fields = self.solr._send_request('get', ADMIN_URL)
  File "C:\Python27\lib\site-packages\pysolr.py", line 331, in _send_request
    raise SolrError(error_message)
mongo_connector.errors.OperationFailed: [Reason: Error 404 Not Found]
***

My steps in trying to connect mongo and solr:

mkdir -p /srv/mongodb/rs0-0 /srv/mongodb/rs0-1 /srv/mongodb/rs0-2 i created the directories a few days ago.

1. cmd
1a. mongod --port 27017 --dbpath /srv/mongodb/rs0-0 --replSet rs0 --smallfiles --oplogSize 128
2. cmd
2a. mongod --port 27018 --dbpath /srv/mongodb/rs0-1 --replSet rs0 --smallfiles --oplogSize 128
3. cmd
3a. mongod --port 27019 --dbpath /srv/mongodb/rs0-2 --replSet rs0 --smallfiles --oplogSize 128
4. cmd
4a. mongo --port 27017
5. cmd
5a. solr start
5b. mongo-connector -m localhost:27017 -t http://localhost:8983/solr -d solr_doc_manager

And than I get the error from above.

**Comment by llvtt** [comment]
That error indicates that mongo-connector couldn't find the URL for the Luke request handler. The URL for Solr should be of the form `http://<host>:<port>/solr/<core name>`. Also make sure you have the Luke request handler set up.

**Comment by llvtt** [comment]
Any update on this? Check out #262 as well, which seems relevant to setting up the LukeRequestHandler.

**Comment by llvtt** [comment]
Closing this issue due to inactivity. Feel free to reopen or create a new issue if there's more to discuss.
