### ISSUE TITLE
InvalidBSON utf8 codec error encountered while replicating data

### ISSUE THREAD

**Issue by guglielmo** [10gen-labs/mongo-connector#269]
After launching the mongo-connector to replicate to an elastic search instance, on the same machine
```
mongo-connector -m localhot:27020 -t localhost:9200 -d elastic_doc_manager
```
A few data are correctly transferred, but I receive this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 490, in do_dump
    upsert_all(dm)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 474, in upsert_all
    dm.bulk_upsert(docs_to_dump(namespace), mapped_ns, long_ts)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 189, in bulk_upsert
    for ok, resp in responses:
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 110, in streaming_bulk
    for action, data in chunk:
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 155, in docs_to_upsert
    for doc in docs:
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 437, in docs_to_dump
    for doc in cursor:
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1090, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1039, in _refresh
    limit, self.__id))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 958, in __send_message
    self.__compile_re)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 121, in _unpack_response
    compile_re)
  File "/usr/local/lib/python2.7/dist-packages/bson/__init__.py", line 537, in decode_all
    tz_aware, uuid_subtype, compile_re))
  File "/usr/local/lib/python2.7/dist-packages/bson/__init__.py", line 331, in _elements_to_dict
    data, position, as_class, tz_aware, uuid_subtype, compile_re)
  File "/usr/local/lib/python2.7/dist-packages/bson/__init__.py", line 320, in _element_to_dict
    data, position, as_class, tz_aware, uuid_subtype, compile_re)
  File "/usr/local/lib/python2.7/dist-packages/bson/__init__.py", line 150, in _get_string
    return _get_c_string(data, position, length - 1)
  File "/usr/local/lib/python2.7/dist-packages/bson/__init__.py", line 113, in _get_c_string
    value = data[position:end].decode("utf-8")
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
InvalidBSON: 'utf8' codec can't decode byte 0xe0 in position 28: invalid continuation byte
```

**Comment by llvtt** [comment]
This is an Exception raised by `pymongo` when it encounters an invalid UTF8 string in a MongoDB document. Do you know what MongoDB driver was used to insert the data you're reading with `mongo-connector`? Some MongoDB drivers don't validate UTF8 when inserting into the database. See #101 for more details.

**Comment by llvtt** [comment]
Closing this issue due to inactivity. Feel free to reopen or create a new issue if there's more to discuss.
