### ISSUE TITLE
mongo-connector try to handle rename command on wrong namespace

### ISSUE THREAD

**Issue by joe-mojo** [10gen-labs/mongo-connector#296]
On my production MongoDB replicaset, every day at 03:00 UTC a map-reduce job produces its results by replacing a result collection.

Every day at the same hour when the map-reduce job is finished, I see an error in mongo-connector log : 

	Unable to process oplog document {u'h': -4643507425017226063, u'ts': Timestamp(1437793202, 743), u'o': {u'to': u'database-name.ResultCollection', u'renameCollection': u'database-name.tmp.mr.queriedCollection_3', u'stayTemp': False}, u'v': 2, u'ns': u'admin.$cmd', u'op': u'c'}
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.6/dist-packages/mongo_connector/oplog_manager.py", line 273, in run timestamp)
	  File "/usr/local/lib/python2.6/dist-packages/mongo_connector/util.py", line 32, in wrapped return f(*args, **kwargs)
	  File "/usr/local/lib/python2.6/dist-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 96, in handle_command "elastic_doc_manager does not support renaming a mapping.")
	OperationFailed: elastic_doc_manager does not support renaming a mapping.

..where "ResultCollection" is the name of tje output collection of the job and "queriedCollection" the name of the input collection. "_3" suffix at the name "queriedCollection_3" seems to be an increment ( the following day I got "_4")

The issue is that my mongo-connector is configured to watch another namespace and this is the only one included namespace. So it should not be reporting this error because it should skip this oplog entry that DOES NOT concern the configured namespace.

**Comment by llvtt** [comment]
Thanks for reporting this! I agree that it's weird that mongo-connector is logging this Exception that has nothing to do with your selected namespaces.

Fortunately, this Exception has no affect at all on mongo-connector behavior except to log a confusing error message. In order to fix this properly, elastic_doc_manager itself will have to know what namespaces you chose in order to decide whether or not a `renameCollection` command is relevant. This will require a little bit of refactoring, so although it's a relatively innocuous bug, it's annoying to fix. I'll include a fix for this in an upcoming 2.2 or 2.1.1 release.

Thanks for your patience and thanks again for reporting this.

**Comment by aherlihy** [comment]
Hi @joe-mojo, I haven't been able to reproduce the issue. Are you still getting this error?

**Comment by AdallomRoy** [comment]
I was able to reproduce it, happens for me in $out collections from an aggregation. (looks like the rename happens with the aggregation was done)

2016-07-27 12:54:20,969 [ERROR] mongo_connector.oplog_manager:317 - Unable to process oplog document {u'h': 5635614354639064659L, u'ts': Timestamp(1469607235, 3589), u'o': {u'to': u'AllTenants.ae_intermediate_aggregation_files_summary_access_1469607233431', u'dropTarget': True, u'renameCollection': u'AllTenants.tmp.agg_out.9205', u'stayTemp': False}, u'v': 2, u'ns': u'AllTenants.$cmd', u'op': u'c'}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.4.1.dev0-py2.7.egg/mongo_connector/oplog_manager.py", line 312, in run
    timestamp)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector-2.4.1.dev0-py2.7.egg/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 97, in handle_command
    "elastic_doc_manager does not support renaming a mapping.")
OperationFailed: elastic_doc_manager does not support renaming a mapping.

**Comment by joe-mojo** [comment]
Sorry, I haven't used mongo-connector for a long time, and next time I'll try kafka-connect for MongoDb and ElasticSearch.
